# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Elizabeth Kiara Regina Ashford

socket_path = "/tmp/luminated-lifx/luminated.sock"
state_path = "/tmp/luminated-lifx/state.json"

[plugin_management]
activation = "explicit"

[[plugins]]
path = "/home/elizabeth/dev/luminate/target/debug/libluminate_plugin_lifx.so"
required = true
